---
- name: Check if the namespace exist
  k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
  register: namespace_exist

- name: Verificar si existe secreto tls default
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ nombre_secreto_tls }}"
    namespace: "{{ namespace }}"
  register: secreto_tls_exist
  when:
    - namespace_exist.resources[0].status.phase is defined

- name: Crear o actualizar secreto {{ nombre_secreto_tls }} - {{ state }}
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'secreto-tls.yaml.j2') }}"
  when:
    - namespace_exist.resources[0].status.phase is defined
    - secreto_tls_exist.resources[0].metadata.creationTimestamp is not defined

- name: Verificar si existe secreto tls default en {{ namespace }}
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ nombre_secreto_tls }}"
    namespace: "{{ namespace }}"
  register: secreto_tls_re_exist
  when:
    - namespace_exist.resources[0].status.phase is defined

- name: Check if the Helm Chart folder exist
  stat:
    path: "{{ helmchart_path }}"
  register: helmchart_path_stat
  when:
    - namespace_exist.resources[0].status.phase is defined
    - secreto_tls_re_exist.resources[0].metadata.creationTimestamp is defined

- name: Ensure {{ output_path  }} exist
  file:
    path: "{{ output_path }}"
    state: directory
  when:
    - namespace_exist.resources[0].status.phase is defined
    - secreto_tls_re_exist.resources[0].metadata.creationTimestamp is defined
    - helmchart_path_stat.stat.exists == true

- name: Read {{ output_path  }} folder
  find:
    paths: "{{ output_path }}"
    patterns: "*"
  register: files_to_delete
  when:
    - namespace_exist.resources[0].status.phase is defined
    - secreto_tls_re_exist.resources[0].metadata.creationTimestamp is defined
    - helmchart_path_stat.stat.exists == true

- name: Delete old files (if it exist)
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  when:
    - namespace_exist.resources[0].status.phase is defined
    - secreto_tls_re_exist.resources[0].metadata.creationTimestamp is defined
    - helmchart_path_stat.stat.exists == true

- name: Create _yaml_ file to overwrite the Chart default values
  template:
    src: ../templates/adjusted_values.yaml.j2
    dest: "{{ output_path }}/adjusted_values.yaml"
  when:
    - namespace_exist.resources[0].status.phase is defined
    - secreto_tls_re_exist.resources[0].metadata.creationTimestamp is defined
    - helmchart_path_stat.stat.exists == true

- name: Deploy the HelmChart
  shell: helm upgrade --install "{{ desired_deployment_name }}" -f "{{ output_path }}/adjusted_values.yaml" "{{ helmchart_path }}/." --namespace "{{ namespace }}"
  when:
    - namespace_exist.resources[0].status.phase is defined
    - secreto_tls_re_exist.resources[0].metadata.creationTimestamp is defined
    - helmchart_path_stat.stat.exists == true

- name: Delete {{ output_path }} as clean up task
  file:
    path: "{{ output_path }}"
    state: absent
  when:
    - namespace_exist.resources[0].status.phase is defined
    - helmchart_path_stat.stat.exists == true
  notify: Nginx Ingress was deployed

- debug:
    msg: The {{ namespace }} namespace does not exist
  when: namespace_exist.resources[0].status.phase is not defined

- debug:
    msg: "The Helm Chart folder does not exists"
  when: helmchart_path_stat.stat.exists == false